config/routes.rb
Rails.application.routes.draw do
  root to: "high_voltage/pages#show", id: "homepage"

  resources :searches, only: [:create, :show]
end

app/models/searcher.rb
class Searcher
  class_attribute :searcher
  self.searcher = Twitter::REST::Client

  attr_reader :results

  def initialize(search_term)
    @results = searcher.new(TWITTER_CONFIG).search(search_term).take(15)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def create
    redirect_to search_path(params[:twitter][:search])
  end

  def show
    @tweets = Searcher.new("##{params[:id]}").results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hashtag</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/homepage.html.erb
<p data-role="description">Search through Twitter!</p>

<%= form_for :twitter, url: searches_path do |form| %>
  <%= form.label :search %>
  <%= form.text_field :search %>

  <%= form.submit "Search" %>
<% end %>

app/views/searches/show.html.erb
<ul>
  <% @tweets.each do |tweet| %>
    <li class="tweet"><%= tweet.text %></li>
  <% end %>
</ul>